#!/bin/bash


# generate a id_rsa file for every programe of git
# when push is needed, just override the default files
# put this script under /usr/bin
# usage: swapssh dns


if [ $# != 1 ] ; then 
	echo "You should specify the github program name"
	exit 1; 
fi 
cd /root/.ssh

TARGET=id_rsa.$1
PUB_TARGET=id_rsa.pub.$1

if [ ! -f $TARGET ] ; then
	echo "target id_rsa file does not exist"
	exit 1
fi

if [ ! -f $PUB_TARGET ] ; then
	echo "target id_rsa.pub file does not exist"
	exit 1
fi

cp $TARGET id_rsa
cp $PUB_TARGET id_rsa.pub
