#!/bin/bash


# generate a id_rsa file for every programe of github
# when push is needed, just override the default files
# put this script under /usr/bin
# usage: swapssh dns

if [ $# != 1 ] ; then 
	echo "You should specify the file extension for github program name"
	exit 1; 
fi

# backup files in case wrong oprations
DEFAULT_BAK="__"
if [ "$1" = "$DEFAULT_BAK" ] ; then
	echo "You can not specify a file name same as default backup's name"
	exit 1
fi

cd ~/.ssh

TARGET=id_rsa.$1
PUB_TARGET=id_rsa.pub.$1

if [ ! -f $TARGET ] ; then
	echo "target id_rsa file does not exist"
	exit 1
fi

if [ ! -f $PUB_TARGET ] ; then
	echo "target id_rsa.pub file does not exist"
	exit 1
fi

# overwrite backup files
cp -f id_rsa id_rsa.__
cp -f id_rsa.pub id_rsa.pub.__

cp $TARGET id_rsa
cp $PUB_TARGET id_rsa.pub
